public class DogClass {

    
    public String name;
    public Double lenth;
    public account acc;
    public list <integer> listNum=new List <Integer> {};
        
        public void show()
   { 
    name='Beka';
    lenth=12.22;
    acc= new Account (name='Moon');
    listNum.add(8);
    listNum.add(9);
       
    system.debug(Name);
    system.debug(lenth);
    system.debug(acc);
    system.debug(listNum);
      
   }
       
}